### ISSUE TITLE
Broken link checking not catching all instances

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/docsite#22]
See - https://github.com/sourcegraph/sourcegraph/pull/5068 and the [OpenGrok migration page](https://github.com/sourcegraph/sourcegraph/blob/master/doc/admin/migration/opengrok.md#deploying-sourcegraph), then click on the **Kubernetes cluster** link for examples.

**Comment by sqs** [comment]
I believe this was caused by link checking being accidentally disabled; see https://github.com/sourcegraph/sourcegraph/pull/6504.
