### ISSUE TITLE
Review markdown rendering

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/docsite#25]

**Comment by sqs** [comment]
Check in https://github.com/russross/blackfriday/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc to see what issues there are. That is the lib we use to render Markdown.

**Comment by ryan-blunden** [comment]
From @ggilmore:

> Can we switch from https://github.com/russross/blackfriday to https://github.com/yuin/goldmark/ ? Hugo even made the switch late last year.

**Comment by unknwon** [comment]
Should be fixed by https://github.com/sourcegraph/docsite/pull/89
