### ISSUE TITLE
JSONC highlighting

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/docsite#46]
We use a lot of JSON, so support for JSONC (JSON with comments) would be nice!

https://github.com/sourcegraph/sourcegraph/pull/11516#discussion_r440570873

**Comment by unknwon** [comment]
Fixed by https://github.com/sourcegraph/docsite/pull/89

<img width="883" alt="CleanShot 2023-02-10 at 14 57 41@2x" src="https://user-images.githubusercontent.com/2946214/218023742-95898a79-e11e-4285-bd87-d94f55b2f430.png">
