### ISSUE TITLE
Sync up footer with the new about site footer

### ISSUE THREAD

**Issue by aileenrose** [sourcegraph/docsite#49]
Update footer links and style to be consistent to about site.

**Comment by kghopson** [comment]
Working on this now. @aileenrose said she's rethinking the logo and would share a design with me in Figma. About footer is located in website/src/components/Footer.tsx

**Comment by aileenrose** [comment]
I believe the footer should only include the copyright and terms/privacy links.   Also, it should be consistent with the footer in Cloud.  I created a design comp here:
https://www.figma.com/file/w7KYhm7fi461grnXjCVzR8/Footer-Documentation-and-Cloud?node-id=0%3A1
