### ISSUE TITLE
Update Sourcegraph logo on docs site to new logo

### ISSUE THREAD

**Issue by lorihey** [sourcegraph/docsite#51]
This logo:

https://docs.sourcegraph.com/assets/sourcegraph-logo-docs.svg

...needs to be replaced with this new one:

https://f.hubspotusercontent20.net/hubfs/2762526/Brand%20assets/sourcegraph-logo.svg

**Comment by kghopson** [comment]
Talked with @aileenrose, apparently the logo that's meant to replace the first one still needs docs on the end. She said she will talk to Victoria to get the logo fixed
