### ISSUE TITLE
Logging bug in the BlackFriday markdown engine re:emphasizing underscore link paths (we can't fix directly; filing for documentation purposes) 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/docsite#64]
Logging [a known bug ](https://github.com/russross/blackfriday/issues/278) on the BlackFriday markdown renderer that I ran into with [this handbook PR](https://github.com/sourcegraph/about/commit/b989d03a9bedf8d5a5d9ccc451f4beaed6e5ad1d)

We can't fix this directly, but I'm logging here to note: 
- This is known, in case someone else comes looking for it
- If a lot of bugs start to pop up with Black Friday, it might be worth looking at using a different library (I don't think we're at that point, but these are the data points we'd want if we had to make that decision someday). A related point to this looked like #25

**Comment by unknwon** [comment]
Confirmed fixed by https://github.com/sourcegraph/docsite/pull/89

<img width="797" alt="CleanShot 2023-02-10 at 14 55 24@2x" src="https://user-images.githubusercontent.com/2946214/218023430-cdd563b6-819b-4a4c-b146-3ca7c50e423b.png">
