### ISSUE TITLE
Semantic difference in our Markdown rendering versus GitHub

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/docsite#69]
GFM allows numbered lists to start without a preceding blank line, but docsite appears to be stricter on this. https://github.com/sourcegraph/about/commit/44c9b331f41afde0639d3f807afbad2abe489c40 shows the change that had to happen for handbook rendering to match GitHub.

Ideally, we should allow both.

**Comment by unknwon** [comment]
Should be fixed by https://github.com/sourcegraph/docsite/pull/89
