### ISSUE TITLE
Use release versions to tag docsite containers additionally to using the latest tag

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/docsite#77]
Presently, images are only tagged with `latest`. Also, when deploying `docs.sourcegraph.com`, we ensure that we're fetching the correct one with the digest. 

The problem is that when we release a new version of docsite, the present process requires to override the `latest` tag, therefore breaking the ability to deploy the previous version if the docker daemon doesn't have it cached locally. 

That's probably fine most of the time, but it could still happen. 

So we could: 

1. Keep the `latest` tag as it is
2. Tag and push on new releases, i.e `v1.8.2` and `latest`
3. Automate image building and pushing in Github Actions

Which would enable us to use the tagged version in our deployment manifests.

**Comment by unknwon** [comment]
Based on what's happening already, I think this is implemented. Also had updated the README to include steps for publishing Docker images with version tags:

<img width="932" alt="CleanShot 2023-02-15 at 11 01 33@2x" src="https://user-images.githubusercontent.com/2946214/218916285-89dcc6cf-90fc-4993-9e23-9a6fd931e606.png">

**Comment by unknwon** [comment]
Release new version of docsite is rather a rare thing today, but it should be [fairly easy](https://github.com/gogs/gogs/blob/main/.github/workflows/docker.yml) to automate docker images publish with GitHub Actions, when we want 😁
