### ISSUE TITLE
Pages not found are yielding a `seo` template error instead of a 404 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/docsite#81]
See 
- this correct URL: https://docs.sourcegraph.com/dev/getting-started/quickstart_2_install_dependencies 
- versus this incorrect URL: https://docs.sourcegraph.com/dev/getting-startwfped/quickstart_2_install_dependencies

**Comment by daxmc99** [comment]
Hit again here with https://docs.sourcegraph.com/dev/getting-started/asdf

**Comment by bobheadxi** [comment]
Hit here as well https://docs.sourcegraph.com/@v124892_2022-01-10_1237dc2/admin/organizations

**Comment by bobheadxi** [comment]
I'm not sure this is an issue with docsite, but an issue with the `sourcegraph/sourcegraph` template: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/_resources/templates/document.html#L3:83
