### ISSUE TITLE
Nil pointer on a certain pages

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/docsite#84]
https://docs.sourcegraph.com/dev/getting-started/quickstart_3_initialize_database#with-docker
causes a nil Pointer reference consistently

We should be resilient to these

**Comment by unknwon** [comment]
<img width="690" alt="CleanShot 2023-02-10 at 14 50 09@2x" src="https://user-images.githubusercontent.com/2946214/218022477-c3eff64b-4c27-425f-9bb6-35aac878516a.png">

I think this should have been resolved by saying the "Page not found". Please feel free to re-open if this is not the case.
