### ISSUE TITLE
Newlines are no longer rendered as a space

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/docsite#91]
A newline in a `.md` file is no longer rendered as a space, leading to unintentionally joined words:

![image](https://user-images.githubusercontent.com/6427795/218441345-95c9700b-12f3-4fef-a138-31a930f11476.png)

Whereas in the source `.md` file it is typed like this:

```
Sourcegraph makes our best effort to use the least amount of calls to your code host. However, it is possible for Sourcegraph 
to encounter rate limits in some scenarios. Please see the specific code host documentation for more information and how to 
mitigate these issues. 
```

This seems to be a regression. Not sure if there's an easy configuration for this in Goldmark

**Comment by unknwon** [comment]
Thanks! 

I believe this is it: https://github.com/sourcegraph/docsite/blob/ff80d07ee68d7c13a5345bb38b2a4ef6ad5f2c35/markdown/markdown.go#L74

**Comment by unknwon** [comment]
Oh wait, this might actually be something else 🤔

**Comment by unknwon** [comment]
@pjlast confirmed fixed on https://docs.sourcegraph.com/admin/external_service#rate-limits
